#!/system/bin/sh
# set cpu parameters


echo '1' > /sys/module/cpu_boost/parameters/input_boost_enabled
echo '40' > /sys/module/cpu_boost/parameters/input_boost_ms
echo '0:1401600 1:0 2:0 3:0 4:140160 5:0 6:0 7:0' > /sys/module/cpu_boost/parameters/input_boost_freq